### ISSUE TITLE
Back button shouldn't go back to a different site

### ISSUE THREAD

**Issue by thibaultmol** [loomchild/sojourner-web#141]
Steps to repro: 
Go to a random website, then go to a specific page on the sojourner site like: https://fosdem.sojourner.rocks/2024/type/Main%20tracks
Then click the back button in the website's ui

What I expect to happen: goes to homepage of the sojourner site
What actually happens: you get back to the previous site you were on.

**Comment by loomchild** [comment]
Thanks for your suggestion.

Actually, it's not trivial, since I can't simply peek what's the previous page in history.

I managed to implement it via `history.state`, but it's not 100% perfect, since if the user refreshes the page, the back button will go back to the dashboard instead of followin the history. But I think it's still worth it.

Please check and let me know what do you think.

**Comment by thibaultmol** [comment]
Works as expected now :+1:
