### ISSUE TITLE
Search result order

### ISSUE THREAD

**Issue by neuhaus** [loomchild/sojourner-web#15]
Please list title matches before other matches

**Comment by loomchild** [comment]
Yeah, that would be nice, but I don't know if you've seen how the search has been implemented :) I am literally serializing all event data to a string and matching all entered keywords to it:
https://github.com/loomchild/sojourner-web/blob/master/src/data/schedule.js#L265

No fancy ranking algorithms, indexes (OK, there's a small optimization), etc. but what is nice it's entirely on client side (so no network required). 

I will think about a better mechanism next year since it's a cool subject, feel free to suggest if you know any front-end technology capable of doing that.

**Comment by loomchild** [comment]
I improved this a bit for 2020 - now title and subtitle are scored higher. The results seem OK, I could go further with a dedicated search library, but I consider that it's good enough for now.

**Comment by neuhaus** [comment]
Thank you!
