### ISSUE TITLE
building for fosdem 2022?

### ISSUE THREAD

**Issue by joe-liad** [loomchild/sojourner-web#92]
Hi, I really loved using sojourner last year! Could you describe how i could rebuild sojourner for 2022 data?

**Comment by loomchild** [comment]
Thanks!

I will do that this weekend, it will be simpler, really sorry for delay.

On January 29, 2022, GitHub ***@***.***> wrote:
> Hi, I really loved using sojourner last year! Could you describe how i
> could rebuild sojourner for 2022 data?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/loomchild/sojourner-web/issues/92>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AATD2HR4QU4EVCC7YSBQOQ3UYPM55ANCNFSM5NC2545Q>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>

**Comment by joe-liad** [comment]
kool thanks, i couldn't install the packages on m1 mac (some built on intel architecture i guess) and closing this ticket. looking forward to using my favourite pwa; the bookmarking feature is a real help when organising which talks to attend!

**Comment by loomchild** [comment]
Hi @joe-liad, the deployment is a bit complicated, therefore not fully documented.
I did a quick update for FOSDEM'22 - you should start seeing this year's talks. I will do a more detailed update on Monday.

**Comment by joe-liad** [comment]
thanks, i've bookmarked some great talks! the page at https://fosdem.org/2022/schedule/mobile/ could be updated to include your pwa in the latest list.

**Comment by loomchild** [comment]
Yes, already done, waiting for confirmation from the staff. Thanks for your help!
